spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycommunity?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: jsbbsj
    username: root
  redis:
    host: 47.100.89.205
    port: 6379
  application:
    name: userApplication
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  session:
    redis:
      flush-mode: immediate

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

server:
  port: 8081